server:
  port:
    9191

spring:
  application:
    name:
      api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: CASHKICK-SERVICE
          uri: lb://CASHKICK-SERVICE
          predicates:
            - Path=/api/v1/cashkicks/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
  instance:
    hostname: localhost